// Frontend permission utilities
export type UserRole = 'ADMIN' | 'HEAD_OF_DEPARTMENT' | 'MANAGER' | 'SUPERVISOR' | 'USER'

export const PERMISSIONS = {
  // User Management
  USER_CREATE: ['ADMIN'],
  USER_UPDATE: ['ADMIN'],
  USER_DELETE: ['ADMIN'],
  USER_VIEW_ALL: ['ADMIN', 'HEAD_OF_DEPARTMENT'],
  USER_VIEW_OWN: ['ADMIN', 'HEAD_OF_DEPARTMENT', 'MANAGER', 'SUPERVISOR', 'USER'],

  // Requests Module
  REQUEST_CREATE: ['ADMIN', 'HEAD_OF_DEPARTMENT', 'MANAGER', 'SUPERVISOR', 'USER'],
  REQUEST_VIEW_ALL: ['ADMIN', 'HEAD_OF_DEPARTMENT', 'MANAGER'],
  REQUEST_VIEW_OWN: ['ADMIN', 'HEAD_OF_DEPARTMENT', 'MANAGER', 'SUPERVISOR', 'USER'],
  REQUEST_APPROVE: ['ADMIN', 'HEAD_OF_DEPARTMENT', 'MANAGER'],
  REQUEST_UPDATE: ['ADMIN', 'HEAD_OF_DEPARTMENT'],
  REQUEST_DELETE: ['ADMIN', 'HEAD_OF_DEPARTMENT'],

  // Recruitment Module
  RECRUITMENT_FORM_CREATE: ['ADMIN', 'HEAD_OF_DEPARTMENT'],
  RECRUITMENT_FORM_UPDATE: ['ADMIN', 'HEAD_OF_DEPARTMENT'],
  RECRUITMENT_FORM_DELETE: ['ADMIN'],
  RECRUITMENT_CAMPAIGN_CREATE: ['ADMIN', 'HEAD_OF_DEPARTMENT', 'MANAGER'],
  RECRUITMENT_CAMPAIGN_UPDATE: ['ADMIN', 'HEAD_OF_DEPARTMENT', 'MANAGER'],
  RECRUITMENT_CANDIDATE_VIEW_ALL: ['ADMIN', 'HEAD_OF_DEPARTMENT', 'MANAGER', 'SUPERVISOR'],
  RECRUITMENT_CANDIDATE_CREATE: ['ADMIN', 'HEAD_OF_DEPARTMENT', 'MANAGER'],
  RECRUITMENT_CANDIDATE_UPDATE: ['ADMIN', 'HEAD_OF_DEPARTMENT', 'MANAGER', 'SUPERVISOR'],
  RECRUITMENT_CANDIDATE_DELETE: ['ADMIN', 'HEAD_OF_DEPARTMENT'],
  RECRUITMENT_PROPOSAL_APPROVE: ['ADMIN', 'HEAD_OF_DEPARTMENT', 'MANAGER'],
  RECRUITMENT_HEADCOUNT_CREATE: ['ADMIN', 'HEAD_OF_DEPARTMENT'],
  RECRUITMENT_HEADCOUNT_UPDATE: ['ADMIN', 'HEAD_OF_DEPARTMENT'],
  RECRUITMENT_DASHBOARD_VIEW: ['ADMIN', 'HEAD_OF_DEPARTMENT', 'MANAGER'],

  // Employees Module
  EMPLOYEE_CREATE: ['ADMIN', 'HEAD_OF_DEPARTMENT'],
  EMPLOYEE_UPDATE: ['ADMIN', 'HEAD_OF_DEPARTMENT', 'MANAGER'],
  EMPLOYEE_VIEW_ALL: ['ADMIN', 'HEAD_OF_DEPARTMENT', 'MANAGER', 'SUPERVISOR'],
  EMPLOYEE_VIEW_OWN: ['ADMIN', 'HEAD_OF_DEPARTMENT', 'MANAGER', 'SUPERVISOR', 'USER'],
  EMPLOYEE_DELETE: ['ADMIN'],
  EMPLOYEE_DASHBOARD_VIEW: ['ADMIN', 'HEAD_OF_DEPARTMENT', 'MANAGER'],

  // Contracts Module
  CONTRACT_CREATE: ['ADMIN', 'HEAD_OF_DEPARTMENT'],
  CONTRACT_UPDATE: ['ADMIN', 'HEAD_OF_DEPARTMENT'],
  CONTRACT_DELETE: ['ADMIN'],
  CONTRACT_VIEW_ALL: ['ADMIN', 'HEAD_OF_DEPARTMENT', 'MANAGER'],
  CONTRACT_VIEW_OWN: ['ADMIN', 'HEAD_OF_DEPARTMENT', 'MANAGER', 'SUPERVISOR', 'USER'],

  // Decisions Module
  DECISION_CREATE: ['ADMIN', 'HEAD_OF_DEPARTMENT'],
  DECISION_UPDATE: ['ADMIN', 'HEAD_OF_DEPARTMENT'],
  DECISION_DELETE: ['ADMIN'],
  DECISION_VIEW_ALL: ['ADMIN', 'HEAD_OF_DEPARTMENT', 'MANAGER', 'SUPERVISOR'],
  DECISION_VIEW_OWN: ['ADMIN', 'HEAD_OF_DEPARTMENT', 'MANAGER', 'SUPERVISOR', 'USER'],

  // Timekeeping Module
  TIMEKEEPING_CREATE: ['ADMIN', 'HEAD_OF_DEPARTMENT', 'MANAGER', 'SUPERVISOR', 'USER'],
  TIMEKEEPING_VIEW_ALL: ['ADMIN', 'HEAD_OF_DEPARTMENT', 'MANAGER', 'SUPERVISOR'],
  TIMEKEEPING_VIEW_OWN: ['ADMIN', 'HEAD_OF_DEPARTMENT', 'MANAGER', 'SUPERVISOR', 'USER'],
  TIMEKEEPING_UPDATE: ['ADMIN', 'HEAD_OF_DEPARTMENT', 'MANAGER'],

  // Payroll Module
  PAYROLL_VIEW_ALL: ['ADMIN', 'HEAD_OF_DEPARTMENT', 'MANAGER'],
  PAYROLL_VIEW_OWN: ['ADMIN', 'HEAD_OF_DEPARTMENT', 'MANAGER', 'SUPERVISOR', 'USER'],
  PAYROLL_CALCULATE: ['ADMIN', 'HEAD_OF_DEPARTMENT'],
  PAYROLL_UPDATE: ['ADMIN', 'HEAD_OF_DEPARTMENT'],

  // Types Management
  TYPE_CREATE: ['ADMIN'],
  TYPE_UPDATE: ['ADMIN'],
  TYPE_DELETE: ['ADMIN'],
} as const

export function hasPermission(userRole: UserRole, permission: keyof typeof PERMISSIONS): boolean {
  return PERMISSIONS[permission].includes(userRole)
}

export function hasAnyPermission(
  userRole: UserRole,
  permissions: Array<keyof typeof PERMISSIONS>
): boolean {
  return permissions.some(permission => PERMISSIONS[permission].includes(userRole))
}

export function hasAllPermissions(
  userRole: UserRole,
  permissions: Array<keyof typeof PERMISSIONS>
): boolean {
  return permissions.every(permission => PERMISSIONS[permission].includes(userRole))
}

